name: axe-core
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  axe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
      - name: setup chrome
        uses: browser-actions/setup-chrome@v1
      - name: Run axe
        run: |
          npm install -g @axe-core/cli
          axe https://www.ck12.org/schools/california/
