name: a11y tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pa11y:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Test using pa11y
        run: |
          npm install -g pa11y
          pa11y https://www.ck12.org/schools/california/
      - name: Test using axe-core
        run: |
          npm install -g @axe-core/cli
          axe https://www.ck12.org/schools/california/
